import { composeExec, type SiteContext } from "../docker.js";
import type { DesignTokens } from "../schemas/design-tokens.js";

export const deps = { composeExec };

export const childThemeFunctionsPath = (slug: string): string => `/var/www/html/wp-content/themes/faktory-${slug}/functions.php`;

/** Gravity Forms Orbital style settings from the tokens (GF only accepts hex values here). */
export function gfStyles(t: DesignTokens): Record<string, string | number> {
  const p = t.palette;
  return {
    theme: "orbital", inputSize: "md", inputBorderRadius: t.radius,
    inputBorderColor: p.contrast3, inputBackgroundColor: p.base3, inputColor: p.contrast, inputPrimaryColor: p.accent,
    labelColor: p.contrast, descriptionColor: p.contrast2,
    buttonPrimaryBackgroundColor: p.accent, buttonPrimaryColor: p.base3,
  };
}

/** Single-quoted PHP string body: only `\` and `'` need escaping. */
const phpQuote = (s: string): string => s.replace(/\\/g, "\\\\").replace(/'/g, "\\'");

/** The child theme's whole functions.php, regenerated on every provision. */
export function childThemeFunctions(slug: string, t: DesignTokens): string {
  const fn = `faktory_${slug.replace(/[^a-z0-9]/g, "_")}`;
  const handle = `faktory-${slug}-style`;
  const font = t.fonts.body.family.replace(/["\\]/g, "");
  const css = `.gform-theme--framework{--gf-font-family:"${font}", sans-serif;}`
    + ".single-post .entry-content{max-width:760px;margin-left:auto;margin-right:auto;}";
  return `<?php
/**
 * Generated by Faktory from design-tokens.json — do not edit: every provision rewrites this file.
 *
 * @package faktory-${slug}
 */

add_action( 'wp_enqueue_scripts', '${fn}_enqueue_styles' );

/**
 * Parent and child stylesheets, plus the token-driven inline CSS.
 */
function ${fn}_enqueue_styles() {
	wp_enqueue_style( 'generatepress-style', get_template_directory_uri() . '/style.css', array(), '0.1.0' );
	wp_enqueue_style( '${handle}', get_stylesheet_directory_uri() . '/style.css', array( 'generatepress-style' ), '0.1.0' );
	wp_add_inline_style( '${handle}', '${phpQuote(css)}' );
}

add_filter( 'gform_default_styles', '${fn}_gform_default_styles' );

/**
 * Gravity Forms Orbital theme settings from the design tokens.
 *
 * @return array
 */
function ${fn}_gform_default_styles() {
	return json_decode( '${phpQuote(JSON.stringify(gfStyles(t)))}', true );
}
`;
}

/** Write functions.php inside the wpcli container (same owner as WordPress files), then lint it. */
export async function installChildTheme(ctx: SiteContext, tokens: DesignTokens): Promise<void> {
  const path = childThemeFunctionsPath(ctx.slug);
  const write = await deps.composeExec(ctx, "wpcli", ["sh", "-c", `cat > ${path}`], { input: childThemeFunctions(ctx.slug, tokens) });
  if (write.code !== 0) throw new Error(`writing ${path} failed: ${(write.stderr || write.stdout).trim()}`);
  const lint = await deps.composeExec(ctx, "wpcli", ["php", "-l", path]);
  if (lint.code !== 0) throw new Error(`php -l ${path} failed: ${(lint.stderr || lint.stdout).trim()}`);
}
