import { describe, it, expect, vi, beforeEach } from "vitest";
import { readFileSync } from "node:fs";
import { loadConfig } from "../../src/config.js";
import { createState } from "../../src/state.js";
import type { SiteContext } from "../../src/docker.js";
import { parseDesignTokens } from "../../src/schemas/design-tokens.js";
import { childThemeFunctions, childThemeFunctionsPath, gfStyles, installChildTheme, deps } from "../../src/provision/child-theme.js";

const tokens = parseDesignTokens(JSON.parse(readFileSync("fixtures/specs/boulangerie.design-tokens.json", "utf8")));
const ctx: SiteContext = { config: loadConfig("/tmp/fk"), slug: "boulangerie-e2e", siteDir: "/tmp/fk/sites/boulangerie-e2e", state: createState("boulangerie-e2e", 8100, "pw") };

describe("gfStyles", () => {
  it("maps the tokens onto Orbital's style keys", () => {
    const p = tokens.palette;
    expect(gfStyles(tokens)).toEqual({
      theme: "orbital", inputSize: "md", inputBorderRadius: tokens.radius,
      inputBorderColor: p.contrast3, inputBackgroundColor: p.base3, inputColor: p.contrast, inputPrimaryColor: p.accent,
      labelColor: p.contrast, descriptionColor: p.contrast2,
      buttonPrimaryBackgroundColor: p.accent, buttonPrimaryColor: p.base3,
    });
  });
});

describe("childThemeFunctions", () => {
  const php = childThemeFunctions("boulangerie-e2e", tokens);
  it("hooks a slug-safe function name at priority 20, without re-enqueueing GP's own stylesheets", () => {
    expect(php.startsWith("<?php\n")).toBe(true);
    expect(php).toContain("Generated by Faktory");
    expect(php).toContain("add_action( 'wp_enqueue_scripts', 'faktory_boulangerie_e2e_enqueue_styles', 20 );");
    expect(php).toContain("function faktory_boulangerie_e2e_enqueue_styles()");
    // GeneratePress already enqueues the child stylesheet as 'generate-child'; the parent style.css
    // is header-only, so neither is re-enqueued here.
    expect(php).not.toContain("wp_enqueue_style(");
    expect(php).not.toContain("get_template_directory_uri()");
  });
  it("returns the GF styles from gform_default_styles as decoded JSON", () => {
    expect(php).toContain("add_filter( 'gform_default_styles', 'faktory_boulangerie_e2e_gform_default_styles' );");
    expect(php).toContain(`return json_decode( '${JSON.stringify(gfStyles(tokens))}', true );`);
  });
  it("sets the GF font and the single post reading width in inline css on GP's 'generate-child' handle", () => {
    expect(php).toContain(`body .gform-theme--framework{--gf-font-family-base:"${tokens.fonts.body.family}", sans-serif;}`);
    expect(php).toContain(".single-post .entry-content{max-width:760px;margin-left:auto;margin-right:auto;}");
    expect(php).toContain("wp_add_inline_style( 'generate-child',");
  });
  it("strips everything but letters, digits and spaces from the font family as defence in depth", () => {
    const odd = { ...tokens, fonts: { ...tokens.fonts, body: { ...tokens.fonts.body, family: `O'Brien</style>}X` } } };
    const out = childThemeFunctions("demo", odd);
    expect(out).toContain(`--gf-font-family-base:"OBrienstyleX", sans-serif;`);
  });
});

describe("installChildTheme", () => {
  beforeEach(() => vi.restoreAllMocks());
  it("writes a .tmp sibling, lints it, then moves it over the live file", async () => {
    const spy = vi.spyOn(deps, "composeExec").mockResolvedValue({ stdout: "No syntax errors detected", stderr: "", code: 0 });
    await installChildTheme(ctx, tokens);
    const path = childThemeFunctionsPath("boulangerie-e2e");
    const tmp = `${path}.tmp`;
    expect(path).toBe("/var/www/html/wp-content/themes/faktory-boulangerie-e2e/functions.php");
    expect(spy.mock.calls[0][1]).toBe("wpcli");
    expect(spy.mock.calls[0][2]).toEqual(["sh", "-c", 'cat > "$1"', "sh", tmp]);
    expect(spy.mock.calls[0][3]?.input).toBe(childThemeFunctions("boulangerie-e2e", tokens));
    expect(spy.mock.calls[1][2]).toEqual(["php", "-l", tmp]);
    expect(spy.mock.calls[2][2]).toEqual(["mv", tmp, path]);
  });
  it("removes the .tmp file and throws with the linter output, leaving the live file untouched, when the file does not parse", async () => {
    const spy = vi.spyOn(deps, "composeExec")
      .mockResolvedValueOnce({ stdout: "", stderr: "", code: 0 })
      .mockResolvedValueOnce({ stdout: "PHP Parse error: syntax error", stderr: "", code: 255 })
      .mockResolvedValueOnce({ stdout: "", stderr: "", code: 0 });
    await expect(installChildTheme(ctx, tokens)).rejects.toThrow(/php -l .*syntax error/);
    const path = childThemeFunctionsPath("boulangerie-e2e");
    const tmp = `${path}.tmp`;
    expect(spy.mock.calls[2][2]).toEqual(["rm", "-f", tmp]);
    expect(spy).toHaveBeenCalledTimes(3);
  });
});
