import { describe, it, expect, vi, beforeEach } from "vitest";
import { readFileSync } from "node:fs";
import { loadConfig } from "../../src/config.js";
import { createState } from "../../src/state.js";
import type { SiteContext } from "../../src/docker.js";
import { parseDesignTokens } from "../../src/schemas/design-tokens.js";
import { childThemeFunctions, childThemeFunctionsPath, gfStyles, installChildTheme, deps } from "../../src/provision/child-theme.js";

const tokens = parseDesignTokens(JSON.parse(readFileSync("fixtures/specs/boulangerie.design-tokens.json", "utf8")));
const ctx: SiteContext = { config: loadConfig("/tmp/fk"), slug: "boulangerie-e2e", siteDir: "/tmp/fk/sites/boulangerie-e2e", state: createState("boulangerie-e2e", 8100, "pw") };

describe("gfStyles", () => {
  it("maps the tokens onto Orbital's style keys", () => {
    const p = tokens.palette;
    expect(gfStyles(tokens)).toEqual({
      theme: "orbital", inputSize: "md", inputBorderRadius: tokens.radius,
      inputBorderColor: p.contrast3, inputBackgroundColor: p.base3, inputColor: p.contrast, inputPrimaryColor: p.accent,
      labelColor: p.contrast, descriptionColor: p.contrast2,
      buttonPrimaryBackgroundColor: p.accent, buttonPrimaryColor: p.base3,
    });
  });
});

describe("childThemeFunctions", () => {
  const php = childThemeFunctions("boulangerie-e2e", tokens);
  it("keeps the parent/child enqueue with slug-safe function names", () => {
    expect(php.startsWith("<?php\n")).toBe(true);
    expect(php).toContain("Generated by Faktory");
    expect(php).toContain("function faktory_boulangerie_e2e_enqueue_styles()");
    expect(php).toContain("'generatepress-style', get_template_directory_uri() . '/style.css'");
    expect(php).toContain("'faktory-boulangerie-e2e-style', get_stylesheet_directory_uri() . '/style.css'");
  });
  it("returns the GF styles from gform_default_styles as decoded JSON", () => {
    expect(php).toContain("add_filter( 'gform_default_styles', 'faktory_boulangerie_e2e_gform_default_styles' );");
    expect(php).toContain(`return json_decode( '${JSON.stringify(gfStyles(tokens))}', true );`);
  });
  it("sets the GF font and the single post reading width in inline css", () => {
    expect(php).toContain(`.gform-theme--framework{--gf-font-family:"${tokens.fonts.body.family}", sans-serif;}`);
    expect(php).toContain(".single-post .entry-content{max-width:760px;margin-left:auto;margin-right:auto;}");
    expect(php).toContain("wp_add_inline_style( 'faktory-boulangerie-e2e-style',");
  });
  it("escapes quotes and backslashes in injected strings", () => {
    const odd = { ...tokens, fonts: { ...tokens.fonts, body: { ...tokens.fonts.body, family: `O'Brien\\Sans "X"` } } };
    const out = childThemeFunctions("demo", odd);
    expect(out).toContain(`--gf-font-family:"O\\'BrienSans X", sans-serif;`);
  });
});

describe("installChildTheme", () => {
  beforeEach(() => vi.restoreAllMocks());
  it("writes the file through the wpcli container, then lints it", async () => {
    const spy = vi.spyOn(deps, "composeExec").mockResolvedValue({ stdout: "No syntax errors detected", stderr: "", code: 0 });
    await installChildTheme(ctx, tokens);
    const path = childThemeFunctionsPath("boulangerie-e2e");
    expect(path).toBe("/var/www/html/wp-content/themes/faktory-boulangerie-e2e/functions.php");
    expect(spy.mock.calls[0][1]).toBe("wpcli");
    expect(spy.mock.calls[0][2]).toEqual(["sh", "-c", `cat > ${path}`]);
    expect(spy.mock.calls[0][3]?.input).toBe(childThemeFunctions("boulangerie-e2e", tokens));
    expect(spy.mock.calls[1][2]).toEqual(["php", "-l", path]);
  });
  it("throws with the linter output when the file does not parse", async () => {
    vi.spyOn(deps, "composeExec")
      .mockResolvedValueOnce({ stdout: "", stderr: "", code: 0 })
      .mockResolvedValueOnce({ stdout: "PHP Parse error: syntax error", stderr: "", code: 255 });
    await expect(installChildTheme(ctx, tokens)).rejects.toThrow(/php -l .*syntax error/);
  });
});
